version: "3"

services:
  grafana:
    image: teslamate/grafana:latest
    container_name: grafana
    restart: always
    labels:
      io.containers.autoupdate: image
    environment:
      # teslamate
      - DATABASE_USER=${TM_DB_USER}
      - DATABASE_PASS=${TM_DB_PASS}
      - DATABASE_NAME=${TM_DB_NAME}
      - DATABASE_HOST=database
      - GRAFANA_PASSWD=${GRAFANA_PASS}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
      # dc-powerwall-dashboard
      #- GF_INSTALL_PLUGINS=grafana-piechart-panel
      #- POWERWALL_LOCATION=${POWERWALL_LOCATION}
      #- VIRTUAL_HOST=${VIRTUAL_HOST}
      #- VIRTUAL_PORT=${VIRTUAL_PORT}
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/dashboards

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    labels:
      io.containers.autoupdate: image
    restart: always
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
  portainer-data:
