apiVersion: 1

datasources:
  - name: PowerWall
    type: influxdb
    orgId: 1
    typeLogoUrl: ""
    access: proxy
    url: http://influxdb:8086
    password: ""
    user: ""
    database: powerwall
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    withCredentials: false
    isDefault: false
    jsonData:
      httpMode: GET
      keepCookies: []
    secureJsonFields: {}
    version: 3
    readOnly: false
